---
- name: configure webservers
  hosts: webservers
  tasks:
    - name: install httpd pkgs
      yum:
        name: httpd
        state: present

    - name: enable httpd service
      service:
        name: httpd
        enabled: yes
        state: started


- name: configure dbservers
  hosts: dbservers
  tasks:
    - name: install mariadb-server pkgs
      yum:
        name: mariadb-server
        state: present

    - name: enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
