# Generated by Django 2.2.12 on 2021-04-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
