# Generated by Django 2.2.12 on 2020-10-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50, unique=True, verbose_name='主机组')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(max_length=50, unique=True, verbose_name='模块')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机')),
                ('ip_addr', models.CharField(max_length=15, verbose_name='IP地址')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_text', models.CharField(max_length=100, verbose_name='参数')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadmin.Module')),
            ],
        ),
    ]
