---
- name: configure webservers
  hosts: webservers
  tasks:
    - name: install httpd pkgs
      yum:
        name: httpd
        state: present

    - name: configure httpd service
      service:
        name: httpd
        state: started
        enabled: yes

- name: configure dbservers
  hosts: dbservers
  tasks:
    - name: install mariadb-server pkgs
      yum:
        name: mariadb-server
        state: present

    - name: configure mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
