# Generated by Django 2.2.12 on 2020-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_addr',
            field=models.CharField(max_length=15),
        ),
    ]
